name: amadon
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks:
  freezed_annotation:
  hooks_riverpod:
  http:
  intl:
  flutter_slidable:
  flutter_svg:
  badges: ^2.0.0-nullsafety.1
  flutter_portal: ^0.4.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:
  pedantic_mono: any
  json_serializable:

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
